### ISSUE TITLE
bf2CC

### ISSUE THREAD

**Issue by nockstarr** [nihlen/bf2-docker#1]
Great initiative!
Do you have plans to include or create a version with bf2CC?

**Comment by nihlen** [comment]
Hey, thanks for the suggestion. I'd like to add BF2CC to a separate branch due to the mono dependency. 
Might get around to it during next week.

**Comment by nockstarr** [comment]
Nice
To potentially save you some time, this is what you need to get the correct mono version running:
`dpkg --add-architecture i386 `  
`apt-get update `  
`apt-get install libglib2.0-0:i386 `  
`wget https://download.mono-project.com/archive/1.1.12.1/linux-installer/0/mono-1.1.12.1_0-installer.bin 
 `
Direct link to bf2CC:  
`wget http://bf2cc.com/dld/client/BF2CC_Client_1.4.2446.zip`

**Comment by nockstarr** [comment]
Forgot to add the modmanager link:
`https://github.com/L2KSolkov/modmanager/archive/master.zip`

**Comment by nihlen** [comment]
The [BF2CC version](/nihlen/bf2-docker/tree/enhanced-bf2cc) should work now. I couldn't find a good direct download for the BF2CC Daemon, only the client, so I'm using a temporary one.

`docker build -t nihlen/bf2-docker/enhanced-bf2cc https://github.com/nihlen/bf2-docker.git#enhanced-bf2cc`
`docker run --name bf2server -it -v <host directory>:/home/bf2/srv -p 80:80/tcp -p 4711:4711/tcp -p 4712:4712/tcp -p 16567:16567/udp -p 27901:27901/udp -p 29900:29900/udp nihlen/bf2-docker/enhanced-bf2cc:latest`

When running it the first time it's a good idea to use interactive mode (-it) since it will generate RCON and BF2CC Daemon admin passwords at the end. But I'll update the readme soon and show what's included in the different versions.

**Comment by nockstarr** [comment]
Great work! Gonna test it this weekend
